### ISSUE TITLE
Please port this to construct 3 runtime

### ISSUE THREAD

**Issue by masscube** [AirConsole/airconsole-construct3#2]
**Please port your plugin to construct 3 runtime:**
https://www.construct.net/en/forum/construct-3/plugin-sdk-10/c3-runtime-sdk-documentation-n-134720

Thanks

**Comment by Psychokiller1888** [comment]
Doesn't change anything

**Comment by SebaSOFT** [comment]
Plugin is not appearing as available when Construct 3 runtime is selected. Could this be the cause?
